/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PatientController;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author gillesferon
 */
public class MainWindow extends javax.swing.JFrame {

    
    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("MISproject2_PU");
    private final PatientController patientCtrl = new PatientController(emfac);
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainWindowLabel = new javax.swing.JLabel();
        doctorTextLabel = new javax.swing.JLabel();
        patientTextLabel = new javax.swing.JLabel();
        VaccinationCenterImageLabel = new javax.swing.JLabel();
        PatientImageLabel = new javax.swing.JLabel();
        VaccinationCenterButton = new javax.swing.JButton();
        PatientButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainWindowLabel.setBackground(new java.awt.Color(0, 0, 153));
        MainWindowLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MainWindowLabel.setForeground(new java.awt.Color(255, 255, 255));
        MainWindowLabel.setText("    Vaccination Center Organizer");
        MainWindowLabel.setOpaque(true);

        doctorTextLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        doctorTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        doctorTextLabel.setText("Vaccination Center");

        patientTextLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        patientTextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        patientTextLabel.setText("Patient");

        VaccinationCenterImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/VaccinationCenter.png"))); // NOI18N

        PatientImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Patient.png"))); // NOI18N

        VaccinationCenterButton.setText("Next");
        VaccinationCenterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaccinationCenterButtonActionPerformed(evt);
            }
        });

        PatientButton.setText("Next");
        PatientButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PatientButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainWindowLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(doctorTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(VaccinationCenterImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(VaccinationCenterButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(patientTextLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(PatientImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(56, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PatientButton)
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainWindowLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(doctorTextLabel)
                    .addComponent(patientTextLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PatientImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VaccinationCenterImageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VaccinationCenterButton)
                    .addComponent(PatientButton))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void refreshPatientList(){
        List patients = patientCtrl.findPatientEntities();
        //EntityListModel<Patient> model = new EntityListModel(patients);
        
        //itemsList.setModel(model);
    }
    private void VaccinationCenterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaccinationCenterButtonActionPerformed
        
        VaccinationCenterWindow vacCenterPopup = new VaccinationCenterWindow();
        vacCenterPopup.setVisible(true);
        
//        vacCenterPopup.addWindowListener(new WindowAdapter() {
//            @Override
//            public void windowClosed(WindowEvent evt){
//                refreshPatientList();
//            }
//        });
    }//GEN-LAST:event_VaccinationCenterButtonActionPerformed

    private void PatientButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PatientButtonActionPerformed
        // TODO add your handling code here:
        PatientWindow patientAddPopup = new PatientWindow();
        patientAddPopup.setVisible(true);
        
        patientAddPopup.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent evt){
                refreshPatientList();
            }
        });
    }//GEN-LAST:event_PatientButtonActionPerformed

  
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MainWindowLabel;
    private javax.swing.JButton PatientButton;
    private javax.swing.JLabel PatientImageLabel;
    private javax.swing.JButton VaccinationCenterButton;
    private javax.swing.JLabel VaccinationCenterImageLabel;
    private javax.swing.JLabel doctorTextLabel;
    private javax.swing.JLabel patientTextLabel;
    // End of variables declaration//GEN-END:variables
}
