/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.PatientController;
import Model.Patient;
import java.awt.event.WindowAdapter;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @author gillesferon
 */
public class PatientWindow extends javax.swing.JPanel {

    /**
     * Creates new form PatientWindow
     */
    public PatientWindow() {
        initComponents();
    }
    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("MISproject2_PU");
    private final PatientController patientCtrl = new PatientController(emfac);
    private Patient patient = null;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VaccinationCenterLabel = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameText = new javax.swing.JTextField();
        MunicipalityLabel = new javax.swing.JLabel();
        MunicipalityText = new javax.swing.JTextField();
        mailAddressLabel = new javax.swing.JLabel();
        mailAddressText = new javax.swing.JTextField();
        nissLabel = new javax.swing.JLabel();
        nissText = new javax.swing.JTextField();
        DisponibilitiesLabel = new javax.swing.JLabel();
        date21 = new javax.swing.JCheckBox();
        date22 = new javax.swing.JCheckBox();
        date23 = new javax.swing.JCheckBox();
        date24 = new javax.swing.JCheckBox();
        date25 = new javax.swing.JCheckBox();
        date26 = new javax.swing.JCheckBox();
        date27 = new javax.swing.JCheckBox();
        date28 = new javax.swing.JCheckBox();
        date29 = new javax.swing.JCheckBox();
        SaveButton = new javax.swing.JButton();

        VaccinationCenterLabel.setBackground(new java.awt.Color(0, 0, 153));
        VaccinationCenterLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VaccinationCenterLabel.setForeground(new java.awt.Color(255, 255, 255));
        VaccinationCenterLabel.setText("   Patient Information");
        VaccinationCenterLabel.setOpaque(true);

        FirstNameLabel.setText("Prénom :");

        FirstNameText.setText("jTextField1");
        FirstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTextActionPerformed(evt);
            }
        });

        LastNameLabel.setText("Nom :");

        LastNameText.setText("jTextField2");
        LastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTextActionPerformed(evt);
            }
        });

        MunicipalityLabel.setText("Commune :");

        MunicipalityText.setText("jTextField3");

        mailAddressLabel.setText("Adresse email :");

        mailAddressText.setText("jTextField4");

        nissLabel.setText("N° de registre national :");

        nissText.setText("jTextField5");

        DisponibilitiesLabel.setText("Disponibilités");

        date21.setText("21 mai 2021");

        date22.setText("22 mai 2021");

        date23.setText("23 mai 2021");

        date24.setText("24 mai 2021");

        date25.setText("25 mai 2021");

        date26.setText("26 mai 2021");

        date27.setText("27 mai 2021");
        date27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                date27ActionPerformed(evt);
            }
        });

        date28.setText("28 mai 2021");

        date29.setText("29 mai 2021");

        SaveButton.setText("Save");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VaccinationCenterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(FirstNameLabel)
                            .addComponent(LastNameLabel)
                            .addComponent(MunicipalityLabel)
                            .addComponent(mailAddressLabel)
                            .addComponent(nissLabel)
                            .addComponent(DisponibilitiesLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nissText, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                            .addComponent(mailAddressText)
                            .addComponent(LastNameText)
                            .addComponent(MunicipalityText)
                            .addComponent(FirstNameText, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date24)
                            .addComponent(date27)
                            .addComponent(date21))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date22)
                            .addComponent(date25)
                            .addComponent(date28))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date26)
                            .addComponent(date29)
                            .addComponent(date23))))
                .addContainerGap(51, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(SaveButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VaccinationCenterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MunicipalityLabel)
                    .addComponent(MunicipalityText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailAddressLabel)
                    .addComponent(mailAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nissLabel)
                    .addComponent(nissText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(DisponibilitiesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date21)
                        .addGap(18, 18, 18)
                        .addComponent(date24)
                        .addGap(18, 18, 18)
                        .addComponent(date27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date22)
                        .addGap(18, 18, 18)
                        .addComponent(date25)
                        .addGap(18, 18, 18)
                        .addComponent(date28))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(date23)
                        .addGap(18, 18, 18)
                        .addComponent(date26)
                        .addGap(18, 18, 18)
                        .addComponent(date29)))
                .addGap(28, 28, 28)
                .addComponent(SaveButton)
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    public void setPatient(Patient patient){
        this.patient = patient;
    }
    public Patient getPatient(){
        updatePatient();
                
        return patient;
    }
    public void updatePatient(){
        if( patient == null ){
            patient = new Patient(); 
            System.out.println("New Patient created");
            System.out.println(patient.getId());
        }
        
        patient.setFirstName(FirstNameText.getText());
        patient.setLastName(LastNameText.getText());
        patient.setNiss(nissText.getText());
        patient.setMunicipality(MunicipalityText.getText());
        patient.setEmail(mailAddressText.getText());
        System.out.println("Info set");
        
    }
    private void LastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTextActionPerformed

    private void date27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_date27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_date27ActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed

        updatePatient();
        //Create patient if necessary
        
        if( patient.getId() == null ){
            patientCtrl.create(patient);           
        }
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    private void FirstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameTextActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisponibilitiesLabel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JLabel MunicipalityLabel;
    private javax.swing.JTextField MunicipalityText;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel VaccinationCenterLabel;
    private javax.swing.JCheckBox date21;
    private javax.swing.JCheckBox date22;
    private javax.swing.JCheckBox date23;
    private javax.swing.JCheckBox date24;
    private javax.swing.JCheckBox date25;
    private javax.swing.JCheckBox date26;
    private javax.swing.JCheckBox date27;
    private javax.swing.JCheckBox date28;
    private javax.swing.JCheckBox date29;
    private javax.swing.JLabel mailAddressLabel;
    private javax.swing.JTextField mailAddressText;
    private javax.swing.JLabel nissLabel;
    private javax.swing.JTextField nissText;
    // End of variables declaration//GEN-END:variables

    
}
