
package View;

import Controller.PatientController;
import Controller.VaccinationCenterController;
import Controller.WaitingListController;
import Model.Patient;
import Model.VaccinationCenter;
import Model.WaitingList;
import Services.HL7Services;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;

/**
 *
 * @authors Rania Charkaoui, Arthur Elskens & Gilles Feron
 */
public class PatientWindow extends javax.swing.JFrame {
    private final EntityManagerFactory emfac = Persistence.createEntityManagerFactory("MISproject2_PU");
    private final PatientController patientCtrl = new PatientController(emfac);
    private final WaitingListController listCtrl = new WaitingListController(emfac);
    private final VaccinationCenterController centerCtrl = new VaccinationCenterController(emfac);
   
    // Initialiazing Patient and WaitingList objects
    private Patient patient = null;
    private WaitingList list = null; 
     // Initialiazing VaccincationCenters with their respective IDs 
    private final VaccinationCenter vaccinationcenter1 = new VaccinationCenter(1);
    private final VaccinationCenter vaccinationcenter2 = new VaccinationCenter(2);
    private final VaccinationCenter vaccinationcenter3 = new VaccinationCenter(3);
    private final VaccinationCenter vaccinationcenter4 = new VaccinationCenter(4);
    
    
    /**
    /**
     * Creates new form PatientWindow
     */
    public PatientWindow() {

        initComponents();
    }
    public void setPatient(Patient patient){
        this.patient = patient;
    }
    public Patient getPatient(){
        updatePatient();       
        return patient;
    }
    public void updatePatient(){
        if( patient == null ){
            patient = new Patient(); 
            //System.out.println("New Patient created");
            
        }

        String municipality = MunicipalityList.getSelectedItem().toString();
        
        patient.setFirstName(FirstNameText.getText());
        patient.setLastName(LastNameText.getText());
        patient.setNiss(nissText.getText());
        patient.setMunicipality(municipality);
        patient.setEmail(mailAddressText.getText());
        
        //System.out.println("Info set");
        
        VaccinationCenter oldCenter = null;
        // Attributing the closestCenter to the patient in function of his/her municipality
        switch (municipality) {
            case "Bruxelles", "Jette", "Ganshoren", "Berchem-Sainte-Agathe", "Koekelberg", "Molenbeek-Saint-Jean" -> oldCenter = centerCtrl.findDuplicate(vaccinationcenter1);
            case "Saint-Josse-ten-Noode", "Schaerbeek", "Evere", "Woluwe-Saint-Lambert" -> oldCenter = centerCtrl.findDuplicate(vaccinationcenter2);
            case "Anderlecht", "Saint-Gilles", "Uccle", "Forest" -> oldCenter = centerCtrl.findDuplicate(vaccinationcenter3);
            case "Etterbeek", "Ixelles", "Woluwe-Saint-Pierre", "Auderghem", "Watermael-Boitsfort" -> oldCenter = centerCtrl.findDuplicate(vaccinationcenter4);
default ->  {
            }
        }
        
        patient.setClosestCenter(oldCenter);
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameText = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameText = new javax.swing.JTextField();
        MunicipalityLabel = new javax.swing.JLabel();
        mailAddressLabel = new javax.swing.JLabel();
        mailAddressText = new javax.swing.JTextField();
        nissLabel = new javax.swing.JLabel();
        nissText = new javax.swing.JTextField();
        SaveButton = new javax.swing.JButton();
        VaccinationCenterLabel = new javax.swing.JLabel();
        DisponibilitiesLabel = new javax.swing.JLabel();
        MunicipalityList = new javax.swing.JComboBox<>();
        hl7_responseLabel = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        FirstNameLabel.setText("Prénom :");

        LastNameLabel.setText("Nom :");

        MunicipalityLabel.setText("Commune :");

        mailAddressLabel.setText("Adresse email :");

        nissLabel.setText("N° de registre national :");

        SaveButton.setText("Enregistrer");
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });

        VaccinationCenterLabel.setBackground(new java.awt.Color(86, 207, 225));
        VaccinationCenterLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        VaccinationCenterLabel.setForeground(new java.awt.Color(255, 255, 255));
        VaccinationCenterLabel.setText("   Informations personnelles");
        VaccinationCenterLabel.setOpaque(true);

        DisponibilitiesLabel.setText("En appuyant sur \"Enregistrer\", j'indique être disponible ces deux prochaines semaines.");

        MunicipalityList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Anderlecht", "Bruxelles", "Ixelles", "Etterbeek", "Evere", "Ganshoren", "Jette", "Koekelberg", "Auderghem", "Schaerbeek", "Berchem-Sainte-Agathe", "Saint-Gilles", "Molenbeek-Saint-Jean", "Saint-Josse-ten-Noode", "Woluwe-Saint-Lambert", "Woluwe-Saint-Pierre", "Uccle", "Forest", "Watermael-Boitsfort" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(VaccinationCenterLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameLabel)
                    .addComponent(LastNameLabel)
                    .addComponent(mailAddressLabel)
                    .addComponent(nissLabel)
                    .addComponent(MunicipalityLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MunicipalityList, 0, 248, Short.MAX_VALUE)
                    .addComponent(nissText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(mailAddressText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LastNameText, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FirstNameText))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(SaveButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hl7_responseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 563, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(DisponibilitiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(VaccinationCenterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstNameLabel)
                    .addComponent(FirstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastNameLabel)
                    .addComponent(LastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(MunicipalityLabel)
                    .addComponent(MunicipalityList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailAddressLabel)
                    .addComponent(mailAddressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nissLabel)
                    .addComponent(nissText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(DisponibilitiesLabel)
                .addGap(18, 18, 18)
                .addComponent(SaveButton)
                .addGap(18, 18, 18)
                .addComponent(hl7_responseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void updateList(){
        if( list == null ){
            list = new WaitingList(); 
//            System.out.println("New patient in List created");

        }
    }
    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        updatePatient();
        Patient oldPatient = patientCtrl.findDuplicate(patient);

        oldPatient.setMunicipality(patient.getMunicipality());
        oldPatient.setClosestCenter(patient.getClosestCenter());
        
        patientCtrl.edit(oldPatient);


        
        if ( HL7Services.sendSRM_S01(oldPatient, "localhost", 54321) ){
            hl7_responseLabel.setText("Votre inscription a bien été prise en compte.\n"
                    + " Vous serez contacté.e.s prochainement.");
        }
        else{
            hl7_responseLabel.setText("Votre demande ne peut pas être reçue actuellement.");
        }
        SaveButton.setEnabled(false);
        
    }//GEN-LAST:event_SaveButtonActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DisponibilitiesLabel;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField FirstNameText;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JTextField LastNameText;
    private javax.swing.JLabel MunicipalityLabel;
    private javax.swing.JComboBox<String> MunicipalityList;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel VaccinationCenterLabel;
    private javax.swing.JLabel hl7_responseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mailAddressLabel;
    private javax.swing.JTextField mailAddressText;
    private javax.swing.JLabel nissLabel;
    private javax.swing.JTextField nissText;
    // End of variables declaration//GEN-END:variables
}
